/*This program is intended to serve as a test for the serial transmission capabilities of the Arduino-Web interface. It transmits one kB
of data generated by the internal clock to the serial bus every 5 seconds.
*/

void setup() {
  // put your setup code here, to run once:
Serial.begin(115200);     //Open serial monitor
}

void loop() {
  // put your main code here, to run repeatedly:
  for (int i = 0; i < 256; i++){
    if (Serial.availableForWrite() >= 4)  Serial.write(micros());             //write uptime in microseconds to serial port. This is a 32 bit unsigned long
  }
  delay(5000);
  }